apiVersion: v1
kind: Service
metadata:
  labels:
   app : myapp
   name: myapp-Svc
spec:
   ports:
     - port: 8080
       protocol: TCP
       targetPort: 8080
   selector:
     app: myapp
     type: NodePort
    
